### PR TITLE
Update to latest version of next.js

### PR DESCRIPTION
**Pull request by heyarne**
Roadmap:

- [x] Fix automatically fixable dependency security issues via `npm audit fix`
- [x] Update to most recent caniuse-lite browser database
- [x] Update to most recent next.js version
- [x] ~~Update to webpack 5, because it will be the default in upcoming versions of next.js~~
- [x] Update to react 17, because it will be the default in upcoming versions of next.js
- [x] Test all components in the storybook
- [x] See if this fixes issue #61

### CODE REVIEW

**Comment by sophiamersmann** [comment]
Note: I just updated next.js to version 10 on a starter-based project and got an error that was related to the css-loader. I haven't investigated further, so not entirely sure this was caused by upgrading next (I didn't get this error when upgrading next on the _Geburtskliniken_ project). Well.. thought this might be useful :)

**Comment by heyarne** [comment]
Webpack 5 support is [still experimental in storybook](https://storybook.js.org/blog/storybook-for-webpack-5/) even though it seems to work fine in next. I'd postpone the webpack update until it becomes more stable, running two separate webpack versions at the same time actually sounds pretty close to what I imagine hell to be like.

**Comment by sophiamersmann** [comment]
I tested this in Lambdatest on Windows 10 + Edge v17
- The map is now rendered
- The storybook doesn't load (the main layout is outlined but the spinner just keeps spinning). Looking in the dev tools gives `Object doesn’t support property or method ‘attachShadow’` as one of many errors but I believe this is the root error. I guess, we'll need a polypfill then (z.B. https://www.npmjs.com/package/@webcomponents/shadydom ? or https://github.com/webcomponents/polyfills ?) but it appears this problem persists only in development (https://github.com/vercel/next.js/issues/13231)

**Comment by heyarne** [comment]
Fair enough! To be honest, rendering the storybook is not a priority in IE. The storybook is part of the developer experience, and I don't see IE playing an important role in that any time soon.

**Pull request merged**
