### PR TITLE
Add dockerfile based on rbb docker alpine

### PR DESCRIPTION
**Pull request by errnesto**
Normally we would export the app to static html and put them on a "static server"

but sometimes it can be usefull to have a real node server generating pages (or images)
So I added a dockerfile which can be used to deploy a rbb-starter-next-js ap in the rbb cluster

### CODE REVIEW

**Review by jengeb — APPROVED** [review]

**Review by jengeb — APPROVED** [review]

**Comment by heyarne** [comment]
I vote against this:

1) Alpine images are not always the smartest idea. See [this blog post](https://pythonspeed.com/articles/alpine-docker-python/) for more info. Maybe we can use another small docker-image, like `debian-slim`?
2) Using node-latest might (and will) break things. This may be OK if we want to see if there are problems with the latest node version, otherwise I'd argue to pin it to a recent stable node version instead.

**Comment by heyarne** [comment]
Aaaah, wait, sorry. This is meant to be the deployment image for the k8s cluster? In that case I'd emphasize point 2.

**Review by heyarne — CHANGES_REQUESTED** [review]
See https://github.com/rbb-data/starter/pull/51#issuecomment-824906177 and https://github.com/rbb-data/starter/pull/51#issuecomment-824914130

**Comment by jengeb** [comment]
Good points! Sounds reasonable to me!

**Comment by sophiamersmann** [comment]
Let's wrap this up if possible?

**Comment by heyarne** [comment]
Simlar to #55: It's good to know that and how this is possible, but so far this was not a common use case, so I'd like to keep it out of the starter.

**Pull request closed without merging**
