### PR TITLE
Add share button component

### PR DESCRIPTION
**Pull request by errnesto**
Maybe we could just use 3 svg icons instead of a icon font
But maybe it just doesn't matter :-)

### CODE REVIEW

**Comment by heyarne** [comment]
>  But maybe it just doesn't matter :-)

I think it doesn't for now. Would be nice to add a story to the storybook!

**Comment by errnesto** [comment]
Hm there is a storybook example… src/components/_shared/ShareButtons/ShareButtons.stories.js
But shure I colud deploy the new storybook before the pull request is merged

**Comment by errnesto** [comment]
But I just found some linter errors:

Line 35:3:  Anchors must have content and the content must be accessible by a screen reader

and
Line 53:5:  Using target="_blank" without rel="noopener noreferrer" is a security risk: see https://mathiasbynens.github.io/rel-noopener 

Ill ad rel="noopener noreferrer" but what about the link text?

**Comment by heyarne** [comment]
See https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/anchor-has-content.md for details on the warning. I suggest adding text content and hiding it via css.

**Comment by heyarne** [comment]
> Hm there is a storybook example… src/components/_shared/ShareButtons/ShareButtons.stories.js
> But shure I colud deploy the new storybook before the pull request is merged

My bad, I didn't see it in the PR. Sorry!

**Pull request merged**
